version: '3.7'

services:
    dev:
        container_name: nestjs_api_prod
        image: atemndobs/nestjs_api_prod:v2
        command: ["sh", "-c", "npm run start"]
        ports:
            - 3000:3000
            - 9229:9229
        restart: always
#        volumes:
#            - .:/usr/src/app
networks:
    default:
        name: laravel_sail
