FROM node:16-alpine3.15 AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk add g++ make py3-pip python3
RUN npm install glob rimraf --force
RUN apk add ffmpeg
RUN pip install pydub

RUN npm install mkdirp@latest

RUN npm install --only=development

RUN npm install -g @nestjs/cli

COPY . .

RUN npm run build

FROM node:16-alpine3.15 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

# 

CMD ["node", "dist/main"]