version: '3.7'

services:
    dev:
        container_name: nestjs_api_dev
        image: atemndobs/nestjs_api_dev:v1
#        build:
#            context: .
#            target: development
#            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - 'nestjs-data:/usr/src/'
        restart: always

#     prod:
#         container_name: nestjs_api_prod
#         image: nestjs_api_prod
#         build:
#             context: .
#             target: production
#             dockerfile: ./Dockerfile
#         command: npm run start:prod
#         ports:
#             - 3000:3000
#             - 9229:9229
#         volumes:
#             - .:/usr/src/app
#             - /usr/src/app/node_modules
#             - 'nestjs-data:/usr/src/'
#         restart: always
networks:
    default:
        name: laravel_sail

volumes:
    nestjs-data:
        driver: local